import type { SiteContent } from "./types";

export const defaultContent: SiteContent = {
  name: "Hall Enoch Asanda",
  role: "Full-Stack Software Engineer",
  location: "Kampala, Uganda",
  headline: "From Figma mockup to App Store release — I build the whole thing.",
  summary:
    "Full-stack engineer with 3+ years shipping production web and mobile apps across real estate, legal-tech, e-commerce, and fintech. Front-ends in React, Next.js, and React Native; back-ends in NestJS and Node.js — delivered end-to-end, in cross-functional agile teams.",
  email: "hallenochasanda@gmail.com",
  whatsapp: "+256 747 640 363",
  booking: "https://calendly.com/hallenochasanda",
  github: "https://github.com/hall-e3",
  linkedin: "https://www.linkedin.com/in/enoch-asanda-hall-839312217/",
  services: [
    {
      id: 1,
      title: "App Development",
      fee: "Project-based quote",
      desc: "End-to-end web and mobile product development — from Figma mockup to App Store release. Front-ends in React, Next.js, and React Native; back-ends in NestJS, Node.js, and PostgreSQL.",
      cta: "View my projects",
    },
    {
      id: 2,
      title: "Tutoring",
      fee: "from $20 / hour",
      desc: "Full-stack programming taught one-on-one: JavaScript, TypeScript, React, React Native, and Node.js — from fundamentals to shipping your first production app. Sessions over Zoom or Google Meet.",
      cta: "Book a session",
    },
    {
      id: 3,
      title: "Consultation",
      fee: "from $50 / session",
      desc: "Insight for founders and teams: product design reviews, system architecture, tech-stack decisions, and realistic estimates of what your system will cost to build and run.",
      cta: "Book a call",
    },
  ],
  projects: [
    {
      id: 2,
      title: "Ffanquest",
      year: "2026",
      platform: "Mobile",
      status: "Live",
      role: "Frontend · React Native",
      link: "https://ffanquest.com/",
      playLink: "https://play.google.com/store/apps/details?id=com.ffanquest.app",
      appStoreLink: "https://apps.apple.com/us/app/ffan-quest/id6778492248",
      tech: ["React Native", "Expo", "TypeScript", "Maps"],
      desc: "Bus travel platform for one-way, round-trip, and multi-city journeys. Passengers book and track trips live on a map; drivers scan digital tickets and manage manifests.",
    },
    {
      id: 3,
      title: "Epic Realty",
      year: "2025",
      platform: "Mobile",
      status: "Live",
      role: "Frontend · React Native",
      link: "https://epicrealtylistings.com/",
      playLink: "https://play.google.com/store/apps/details?id=com.epicrealty.app",
      appStoreLink: "https://apps.apple.com/us/app/epic-realty/id6763585116",
      tech: ["React Native", "Expo", "Gluestack UI", "TypeScript"],
      desc: "Property rental platform connecting owners and renters. Architected the core structure and component patterns adopted team-wide; shipped to both app stores.",
    },
    {
      id: 1,
      title: "Herbel — Organic Plug",
      year: "2025 – 26",
      platform: "Web",
      status: "Live",
      role: "Full-stack · solo build",
      link: "https://organicplugug.com/",
      tech: ["Next.js", "NestJS", "TypeORM", "PostgreSQL", "Tailwind CSS", "SendGrid"],
      desc: "Complete e-commerce stack — storefront, admin dashboard, and REST API — with live product search, multi-step checkout, and automated transactional email.",
    },
    {
      id: 8,
      title: "KASI Technical Services",
      year: "2026",
      platform: "Web",
      status: "Live",
      role: "Frontend",
      link: "https://kasitechnicalserviceslimited.com/",
      tech: ["Next.js", "SEO", "Responsive"],
      desc: "Corporate site for a Ugandan electrical engineering & civil works contractor (33kV works, power lines, solar street lighting) trusted by Bank of Uganda, UETCL, and UNBS — services, project portfolio, certifications, and quote requests.",
    },
    {
      id: 6,
      title: "BE8",
      year: "2025",
      platform: "Web",
      status: "Live",
      role: "Full Stack Developer",
      link: "https://be8ug.com/",
      tech: ["NextJS", "NestJS", "Postgresql", "Typeorm"],
      desc: "An online grocery delivery service for Uganda (it offers ordering of fresh groceries, household essentials, and beverages online, with fast delivery across Uganda and daily deals and coupons).",
    },
    {
      id: 5,
      title: "Find It",
      year: "2025 – now",
      platform: "Web",
      status: "In development",
      role: "Full-stack · personal",
      link: "https://findit-landing-page.onrender.com",
      tech: ["Node.js", "MongoDB", "OCR", "Cypress"],
      desc: "Lost-document recovery system helping citizens retrieve student IDs, national IDs, and driver's licenses — OCR automates data extraction; tested end-to-end with Cypress.",
    },
    {
      id: 9,
      title: "Be-Hurry — Microfinance Loan Management System",
      year: "2026",
      platform: "Web",
      status: "Live",
      role: "Full Stack Developer",
      link: "https://behurryug.com/",
      tech: ["Nestjs", "Typeorm", "Nextjs", "Postgresql"],
      desc: "A full-stack loan management platform built for microfinance operations, handling the complete loan lifecycle from client onboarding through disbursement, repayment tracking, and cash reconciliation. Built as a pnpm/Turborepo monorepo with three applications sharing a common design system and type library.",
    },
  ],
  skills: [
    {
      id: 1,
      label: "Front-End",
      items: "React.js · Next.js · React Native · TypeScript · Redux Toolkit · TanStack Query · Flutter · Tailwind CSS",
    },
    {
      id: 2,
      label: "Back-End",
      items: "Node.js · NestJS · Express.js · Django · REST APIs · GraphQL · TypeORM",
    },
    {
      id: 3,
      label: "Databases",
      items: "PostgreSQL · MongoDB · MySQL · SQLite",
    },
    {
      id: 4,
      label: "DevOps & Tools",
      items: "Docker · Kubernetes · GitHub Actions · GitLab CI/CD · Vercel · AWS · Figma · Cypress · Jest",
    },
  ],
};
