import type { SiteContent } from "./types";

export const defaultContent: SiteContent = {
  name: "Hall Enoch Asanda",
  role: "Full-Stack Software Engineer",
  location: "Kampala, Uganda",
  headline: "From Figma mockup to App Store release — I build the whole thing.",
  summary:
    "Full-stack engineer with 3+ years shipping production web and mobile apps across real estate, legal-tech, e-commerce, and fintech. Front-ends in React, Next.js, and React Native; back-ends in NestJS and Node.js — delivered end-to-end, in cross-functional agile teams.",
  email: "hallenochasanda@gmail.com",
  whatsapp: "+256 747 640 363",
  booking: "https://calendly.com/hallenochasanda",
  github: "https://github.com/hall-e3",
  linkedin: "https://www.linkedin.com/in/enoch-asanda-hall-839312217/",
  services: [
    {
      id: 1,
      title: "App Development",
      fee: "Project-based quote",
      desc: "End-to-end web and mobile product development — from Figma mockup to App Store release. Front-ends in React, Next.js, and React Native; back-ends in NestJS, Node.js, and PostgreSQL.",
      cta: "View my projects",
    },
    {
      id: 2,
      title: "Tutoring",
      fee: "from $20 / hour",
      desc: "Full-stack programming taught one-on-one: JavaScript, TypeScript, React, React Native, and Node.js — from fundamentals to shipping your first production app. Sessions over Zoom or Google Meet.",
      cta: "Book a session",
    },
    {
      id: 3,
      title: "Consultation",
      fee: "from $50 / session",
      desc: "Insight for founders and teams: product design reviews, system architecture, tech-stack decisions, and realistic estimates of what your system will cost to build and run.",
      cta: "Book a call",
    },
  ],
  projects: [
    {
      id: 9,
      title: "Be-Hurry — Microfinance Loan Management System",
      year: "2026",
      platform: "Web",
      status: "Live",
      role: "Full Stack Developer",
      link: "https://behurryug.com/",
      tech: ["Nestjs", "Typeorm", "Nextjs", "Postgresql", "Turborepo"],
      desc: "A full-stack loan management platform built for microfinance operations, handling the complete loan lifecycle from client onboarding through disbursement, repayment tracking, and cash reconciliation. Built as a pnpm/Turborepo monorepo with three applications sharing a common design system and type library.",
      tagline: "Enterprise Monorepo Loan Lifecycle & Cash Reconciliation System",
      proposalScope: "Delivered a multi-app monorepo system comprising an Admin Dashboard, Client Portal, and Field Officer interface, complete with cash reconciliation algorithms and audit logs.",
      architecture: {
        overview: "Architected as a pnpm/Turborepo monorepo sharing core DTOs, validation schemas, and `@behurry/ui` component packages across 3 web applications. Powered by NestJS, TypeORM, and PostgreSQL on the backend, and Next.js App Router on the frontend.",
        frontend: "Next.js App Router (TypeScript) with TanStack Query for state synchronization, custom virtualized financial tables, and atomic Tailwind CSS components.",
        backend: "NestJS microservices with domain-driven design, TypeORM entities, and PostgreSQL with strict transactional isolation to guarantee financial ledger integrity.",
        database: "PostgreSQL relational database with indexed query plans for fast loan reporting, daily session balance tracking, and immutable audit logs.",
        infrastructure: "Dockerized container deployment with GitHub Actions CI/CD pipelines and zero-downtime database migration scripts.",
        highlights: [
          "Atomic daily session closing balances to prevent capital cross-day carryover errors",
          "Shared monorepo type system ensuring 100% contract alignment between frontend & backend",
          "Automated interest rate & repayment schedule calculators",
          "Role-based access control for loan officers, managers, and cashiers",
        ],
      },
      sdlc: {
        methodology: "Domain-Driven Agile SDLC (2-week Sprints) with bi-weekly stakeholder reviews.",
        planningAndThoughts: "Before starting implementation, I mapped out the entire microfinance financial domain—identifying critical race conditions during cash reconciliation and daily closing. I designed strict finite state machine transitions for loan statuses (Draft -> Under Review -> Approved -> Disbursed -> Active -> Repaid / Defaulted) to guarantee operational consistency.",
        qualityAssurance: "Strict TypeScript strict mode, Zod runtime payload validation, Jest unit tests for interest calculation formulas, and manual end-to-end sanity testing on all financial workflows.",
        deploymentStrategy: "Monorepo CI build verification, automated database schema migration checks, and seamless static deployment on production CDNs.",
      },
      challenges: [
        {
          title: "Cross-Day Financial Capital Carryover Errors",
          problem: "Legacy financial systems suffered from ledger leakage where walk-in cash transactions and unassigned loan disbursements bled into subsequent business day reports.",
          solution: "Implemented an atomic 'Open New Day' session locking workflow that captures the previous day's closing balance immutably and enforces strict session boundary locks on all transactions.",
        },
        {
          title: "Monorepo Code Duplication Across 3 Applications",
          problem: "Maintaining separate form validations and table components across Admin, Client, and Officer apps threatened to create UI drift and double maintenance work.",
          solution: "Extracted all shared form controls, validation rules, and design tokens into `@behurry/ui` and `@behurry/common` monorepo packages, enabling single-source-of-truth component reuse.",
        },
      ],
      timeline: [
        { phase: "Phase 1: Domain Analysis & Monorepo Setup", duration: "Month 1", deliverables: "Financial state machine design, Turborepo setup, database entity modeling." },
        { phase: "Phase 2: Core Backend API & Shared UI Library", duration: "Months 2–3", deliverables: "NestJS loan lifecycle endpoints, TypeORM migrations, @behurry/ui package." },
        { phase: "Phase 3: Dashboard & Cash Reconciliation Engine", duration: "Month 4", deliverables: "Admin dashboard, daily closing balance workflow, reporting views." },
        { phase: "Phase 4: QA, Testing & Production Release", duration: "Month 5", deliverables: "Financial calculation verification, user training, live deployment at behurryug.com." },
      ],
      maintenanceAndAvailability: {
        status: "Actively Maintained & Operational in Production",
        clientCommitment: "Ongoing maintenance is handled via structured weekly maintenance windows and automated monitoring, requiring minimal daily intervention.",
        availabilityNotice: "🟢 Available for new full-stack engineering roles, software architecture contracts, and enterprise monorepo projects without conflict.",
      },
    },
    {
      id: 2,
      title: "Ffanquest",
      year: "2026",
      platform: "Mobile",
      status: "Live",
      role: "Frontend · React Native",
      link: "https://ffanquest.com/",
      playLink: "https://play.google.com/store/apps/details?id=com.ffanquest.app",
      appStoreLink: "https://apps.apple.com/us/app/ffan-quest/id6778492248",
      tech: ["React Native", "Expo", "TypeScript", "Maps"],
      desc: "Bus travel platform for one-way, round-trip, and multi-city journeys. Passengers book and track trips live on a map; drivers scan digital tickets and manage manifests.",
      tagline: "Real-Time Multi-City Bus Booking & Live Fleet Tracking App",
      proposalScope: "Built the cross-platform mobile user interfaces for both passengers and drivers, including interactive seat selection, live map tracking, and offline camera ticket scanning.",
      architecture: {
        overview: "Cross-platform mobile application engineered with React Native and Expo, connected to a real-time Node.js backend using WebSockets and Google Maps SDK.",
        frontend: "React Native with Expo framework, custom vector map overlays, animated marker interpolations, and camera-based QR ticket scanner.",
        backend: "Node.js REST API with WebSocket event emitters for real-time bus GPS coordinates.",
        database: "PostgreSQL with spatial indexing for geo-radius passenger route searches.",
        infrastructure: "Expo Application Services (EAS) for automated iOS & Android app store builds and Over-The-Air (OTA) updates.",
        highlights: [
          "Live GPS vehicle tracking on interactive maps with smooth position interpolation",
          "Driver QR code digital ticket scanner working in low-connectivity terminal environments",
          "Multi-city travel routing with dynamic fare calculators",
        ],
      },
      sdlc: {
        methodology: "Iterative Mobile Agile Development with continuous Expo TestFlight builds.",
        planningAndThoughts: "Analyzed driver environment constraints (low light, intermittent network) versus passenger needs (accurate arrival predictions). Structured offline-first ticket scanning cache to ensure zero boarding delays at bus terminals.",
        qualityAssurance: "TypeScript interface contracts, physical device testing across iOS and Android models, and automated build verification.",
        deploymentStrategy: "Expo EAS Build pipelines submitted directly to Apple App Store Connect and Google Play Console.",
      },
      challenges: [
        {
          title: "High Battery Consumption & GPS Location Jitter",
          problem: "Continuous high-frequency GPS tracking on driver phones drained batteries quickly and caused marker jumping on passenger maps.",
          solution: "Implemented adaptive distance-filtered geolocation updates and velocity smoothing, reducing location payloads by 60% while maintaining smooth map animations.",
        },
      ],
      timeline: [
        { phase: "Phase 1: UX Wireframes & Map Prototype", duration: "Weeks 1–3", deliverables: "Interactive map prototype, seat selection UI design." },
        { phase: "Phase 2: Passenger Booking & Driver Scanner", duration: "Weeks 4–8", deliverables: "Ticket generation engine, driver QR scanning module." },
        { phase: "Phase 3: Beta Testing & Store Publishing", duration: "Weeks 9–12", deliverables: "App Store & Play Store approval and live release." },
      ],
      maintenanceAndAvailability: {
        status: "Live on Apple App Store & Google Play Store",
        clientCommitment: "SLA maintenance managed via automated OTA updates and scheduled feature releases.",
        availabilityNotice: "🟢 Fully available for new React Native / Expo mobile app projects and contract roles.",
      },
    },
    {
      id: 3,
      title: "Epic Realty",
      year: "2025",
      platform: "Mobile",
      status: "Live",
      role: "Frontend · React Native",
      link: "https://epicrealtylistings.com/",
      playLink: "https://play.google.com/store/apps/details?id=com.epicrealty.app",
      appStoreLink: "https://apps.apple.com/us/app/epic-realty/id6763585116",
      tech: ["React Native", "Expo", "Gluestack UI", "TypeScript"],
      desc: "Property rental platform connecting owners and renters. Architected the core structure and component patterns adopted team-wide; shipped to both app stores.",
      tagline: "Multi-Tenant Property Marketplace with Shipped Mobile Apps",
      proposalScope: "Lead the frontend mobile architecture design, establishing design system token patterns and component conventions for a team of 3 developers.",
      architecture: {
        overview: "Modular React Native mobile application utilizing Gluestack UI for standard accessible styling and Expo for native device capabilities.",
        frontend: "React Native, Expo, Gluestack UI, TypeScript atomic component design.",
        highlights: [
          "Team-wide standardized component architecture pattern",
          "Optimized image gallery carousel for property listings",
          "Deep-linking for instant social media property sharing",
        ],
      },
      sdlc: {
        methodology: "Scrum Agile with sprint component reviews.",
        planningAndThoughts: "Designed reusable UI components early to prevent merge conflicts among team members, enabling fast parallel development.",
        qualityAssurance: "Snapshot testing with Jest and physical device testing.",
        deploymentStrategy: "App Store Connect & Google Play Console automated releases.",
      },
      challenges: [
        {
          title: "Memory Spikes During Heavy Listing Carousel Scrolling",
          problem: "High-resolution property images caused memory growth when users scrolled through long property feeds.",
          solution: "Implemented windowed list rendering with image memory recycling and dynamic thumbnail downsampling.",
        },
      ],
      timeline: [
        { phase: "Phase 1: Architecture & Design Tokens", duration: "Month 1", deliverables: "Gluestack UI setup, core component library." },
        { phase: "Phase 2: Property Search & Listing Engine", duration: "Months 2–3", deliverables: "Listing detail views, filter controls, chat integration." },
        { phase: "Phase 3: Store Approvals & Launch", duration: "Month 4", deliverables: "App Store and Google Play live publishing." },
      ],
      maintenanceAndAvailability: {
        status: "Live Production Shipped Application",
        clientCommitment: "Routine maintenance and bug-fix SLA managed efficiently.",
        availabilityNotice: "🟢 Open for new mobile development projects and full-stack software consulting.",
      },
    },
    {
      id: 1,
      title: "Herbel — Organic Plug",
      year: "2025 – 26",
      platform: "Web",
      status: "Live",
      role: "Full-stack · solo build",
      link: "https://organicplugug.com/",
      tech: ["Next.js", "NestJS", "TypeORM", "PostgreSQL", "Tailwind CSS", "SendGrid"],
      desc: "Complete e-commerce stack — storefront, admin dashboard, and REST API — with live product search, multi-step checkout, and automated transactional email.",
      tagline: "End-to-End E-Commerce Stack (Storefront, Admin CMS & REST API)",
      proposalScope: "Solely designed, engineered, and deployed the full e-commerce ecosystem, including product catalog, checkout, order notifications, and admin management.",
      architecture: {
        overview: "Decoupled architecture with Next.js App Router for frontend storefront & admin dashboard, communicating with a NestJS backend REST API.",
        frontend: "Next.js (TypeScript), Tailwind CSS, optimistic UI state management.",
        backend: "NestJS, TypeORM, PostgreSQL, SendGrid transactional mail integration.",
        highlights: [
          "Instant client-side fuzzy product search and filter",
          "Automated transactional emails for order confirmations & status changes",
          "Responsive mobile-first storefront design",
        ],
      },
      sdlc: {
        methodology: "Solo Rapid Prototyping to Production Deployment.",
        planningAndThoughts: "Focused on seamless customer purchase flow and easy product management for non-technical admins.",
        qualityAssurance: "End-to-end checkout flow testing and database migration verification.",
        deploymentStrategy: "Vercel edge hosting for Next.js app and cloud server deployment for NestJS API.",
      },
      challenges: [
        {
          title: "Stock Reservation Concurrency During Flash Sales",
          problem: "Risk of overselling product items during concurrent multi-step checkout attempts.",
          solution: "Enforced database transaction locks and optimistic stock checks prior to order placement.",
        },
      ],
      timeline: [
        { phase: "Phase 1: Backend API & Database Schemas", duration: "Weeks 1–4", deliverables: "NestJS catalog & order API, TypeORM PostgreSQL setup." },
        { phase: "Phase 2: Storefront & Admin Dashboard", duration: "Weeks 5–8", deliverables: "Next.js storefront, multi-step checkout, admin inventory CMS." },
        { phase: "Phase 3: Launch & Transactional Emailing", duration: "Weeks 9–10", deliverables: "Live release at organicplugug.com and SendGrid integration." },
      ],
      maintenanceAndAvailability: {
        status: "Live Operational E-Commerce Store",
        clientCommitment: "Self-sustaining production system with automated transactional emails.",
        availabilityNotice: "🟢 Available for full-stack e-commerce, web application, and custom software builds.",
      },
    },
    {
      id: 8,
      title: "KASI Technical Services",
      year: "2026",
      platform: "Web",
      status: "Live",
      role: "Frontend",
      link: "https://kasitechnicalserviceslimited.com/",
      tech: ["Next.js", "SEO", "Responsive"],
      desc: "Corporate site for a Ugandan electrical engineering & civil works contractor (33kV works, power lines, solar street lighting) trusted by Bank of Uganda, UETCL, and UNBS — services, project portfolio, certifications, and quote requests.",
      tagline: "High-Performance Corporate Engineering Contractor Portal",
      proposalScope: "Designed and implemented a fast, accessible corporate web application showcasing heavy civil & electrical engineering projects for government and corporate clients.",
      architecture: {
        overview: "Next.js static site architecture optimized for speed, accessibility, and search engine visibility.",
        frontend: "Next.js, TypeScript, Tailwind CSS, WebP image asset pipeline.",
        highlights: [
          "Sub-second page load times across mobile networks",
          "Structured JSON-LD schema metadata for search engine indexing",
          "Interactive project portfolio showcase and quote request forms",
        ],
      },
      sdlc: {
        methodology: "Waterfall Client Discovery to Agile Iterative Design.",
        planningAndThoughts: "Organized complex technical contractor certifications, project portfolios, and compliance documentation into an intuitive navigation structure.",
        qualityAssurance: "Lighthouse performance audits scoring 95+ across SEO, Accessibility, and Performance.",
        deploymentStrategy: "Automated Vercel deployment with continuous deployment from main git branch.",
      },
      challenges: [
        {
          title: "High Image Payload Causing Slow LCP Scores",
          problem: "High-resolution photography of 33kV power line installations degraded mobile load performance.",
          solution: "Implemented Next.js dynamic image optimization, automatic WebP conversion, and responsive picture breakpoints.",
        },
      ],
      timeline: [
        { phase: "Discovery & Content Structuring", duration: "Week 1", deliverables: "Information architecture and wireframes." },
        { phase: "Frontend Build & SEO", duration: "Week 2", deliverables: "Next.js components, SEO metadata implementation." },
        { phase: "Launch & Sign-off", duration: "Week 3", deliverables: "Production launch at kasitechnicalserviceslimited.com." },
      ],
      maintenanceAndAvailability: {
        status: "Live Corporate Website",
        clientCommitment: "Fully operational static deployment requiring zero ongoing server maintenance.",
        availabilityNotice: "🟢 Readily available for high-tier corporate web applications and frontend contracts.",
      },
    },
    {
      id: 6,
      title: "BE8",
      year: "2025",
      platform: "Web",
      status: "Live",
      role: "Full Stack Developer",
      link: "https://be8ug.com/",
      tech: ["NextJS", "NestJS", "Postgresql", "Typeorm"],
      desc: "An online grocery delivery service for Uganda (it offers ordering of fresh groceries, household essentials, and beverages online, with fast delivery across Uganda and daily deals and coupons).",
      tagline: "Online Grocery Delivery & Coupon Engine Platform",
      proposalScope: "Developed product catalog search, delivery scheduling logic, and custom coupon discount engines.",
      architecture: {
        overview: "Next.js frontend connected to NestJS microservices backend with PostgreSQL persistence.",
        frontend: "Next.js App Router, Tailwind CSS, stateful cart management.",
        backend: "NestJS, TypeORM, Redis caching for active promotion coupons.",
        highlights: [
          "Dynamic daily deals and coupon discount application engine",
          "Fast grocery item search with category filters",
        ],
      },
      sdlc: {
        methodology: "Agile Sprints with continuous feedback.",
        planningAndThoughts: "Focused on high re-order conversion rates and fast checkout for daily essentials.",
        qualityAssurance: "Automated API route testing and cart verification.",
        deploymentStrategy: "Cloud web application hosting.",
      },
      challenges: [
        {
          title: "Handling Coupon Code Concurrency & Expiration",
          problem: "Preventing expired or over-used discount coupons from passing checkout validation.",
          solution: "Utilized Redis cache for high-speed coupon validation and database transactions during final checkout.",
        },
      ],
      timeline: [
        { phase: "Phase 1: Catalog & Checkout Engine", duration: "Months 1–2", deliverables: "Grocery catalog, cart, and payment API." },
        { phase: "Phase 2: Coupon Engine & Delivery Logistics", duration: "Month 3", deliverables: "Coupon engine, address locator, live release." },
      ],
      maintenanceAndAvailability: {
        status: "Live Operational E-Commerce Platform",
        clientCommitment: "Maintained in active production.",
        availabilityNotice: "🟢 Available for full-stack software development and e-commerce engineering.",
      },
    },
    {
      id: 5,
      title: "Find It",
      year: "2025 – now",
      platform: "Web",
      status: "In development",
      role: "Full-stack · personal",
      link: "https://findit-landing-page.onrender.com",
      tech: ["Next.js", "MongoDB", "Nodemailer", "Redis", "Node.js", "Express", "Tesseract OCR", "Cypress"],
      desc: "Lost-document recovery system helping citizens retrieve student IDs, national IDs, and driver's licenses — powered by Next.js, Node.js, Express, MongoDB, Nodemailer, Redis, and a Tesseract OCR computer vision pipeline; tested end-to-end with Cypress.",
      tagline: "Automated OCR Lost-Document Extraction & Matching Engine",
      proposalScope: "Personal R&D initiative to automate data extraction from uploaded photographs of lost identity documents using computer vision.",
      architecture: {
        overview: "Full-stack architecture featuring a Next.js web application coupled with a Node.js / Express backend service, MongoDB document persistence, Redis caching, Nodemailer transactional mailer, and Tesseract OCR engine.",
        frontend: "Next.js App Router (TypeScript) with drag-and-drop document upload interface.",
        backend: "Node.js, Express REST API, Tesseract OCR computer vision processing pipeline, MongoDB database, Nodemailer notification engine, and Redis cache layer.",
        database: "MongoDB document store holding encrypted user records and document metadata matches.",
        infrastructure: "Redis cache for rapid match candidate lookups and Render hosting with automated Cypress E2E test runs.",
        highlights: [
          "Automated OCR text extraction from damaged document photographs",
          "Redis caching for high-speed document search matching",
          "Nodemailer integration for automated match notifications",
          "End-to-end test suite written in Cypress",
          "Privacy-focused document masking and secure matching algorithms",
        ],
      },
      sdlc: {
        methodology: "Test-Driven Development (TDD) & Computer Vision R&D.",
        planningAndThoughts: "Designed to solve the widespread problem of lost national IDs in Uganda through automated document parsing and notification alerts.",
        qualityAssurance: "Comprehensive Cypress E2E test suites covering image upload, pre-processing, and OCR text matching.",
        deploymentStrategy: "Automated CI pipeline running Cypress tests before deployment to Render cloud platform.",
      },
      challenges: [
        {
          title: "Low OCR Accuracy on Damaged & Glared Document Images",
          problem: "Phone photos of plastic IDs often suffered from glare and low contrast, resulting in garbled text.",
          solution: "Built an automated image pre-processing pipeline (grayscale conversion, adaptive thresholding, and contrast sharpening) prior to OCR parsing.",
        },
        {
          title: "Real-Time Notification & Matching Performance",
          problem: "Parsing high volumes of document scans without slowing down email match alerts.",
          solution: "Integrated Redis caching for match indexing and offloaded email delivery to Nodemailer background jobs.",
        },
      ],
      timeline: [
        { phase: "Phase 1: OCR Computer Vision Prototype", duration: "Month 1", deliverables: "Image preprocessing and Tesseract integration." },
        { phase: "Phase 2: Next.js UI, Redis & Nodemailer Integration", duration: "Month 2", deliverables: "Next.js portal, Redis cache, Nodemailer notifications." },
        { phase: "Phase 3: Cypress E2E Testing & Public Pilot", duration: "Month 3–Present", deliverables: "Cypress automated test suite, live pilot at findit-landing-page.onrender.com." },
      ],
      maintenanceAndAvailability: {
        status: "In Active R&D / Pilot Development",
        clientCommitment: "Personal innovation project.",
        availabilityNotice: "Open for technical contracts, full-stack roles, and AI/document processing consulting.",
      },
    },
  ],
  skills: [
    {
      id: 1,
      label: "Front-End",
      items: "React.js · Next.js · React Native · TypeScript · Redux Toolkit · TanStack Query · Flutter · Tailwind CSS",
    },
    {
      id: 2,
      label: "Back-End",
      items: "Node.js · NestJS · Express.js · Django · REST APIs · GraphQL · TypeORM",
    },
    {
      id: 3,
      label: "Databases",
      items: "PostgreSQL · MongoDB · MySQL · SQLite",
    },
    {
      id: 4,
      label: "DevOps & Tools",
      items: "Docker · Kubernetes · GitHub Actions · GitLab CI/CD · Vercel · AWS · Figma · Cypress · Jest",
    },
  ],
};
